# Generated by Django 3.1.5 on 2021-01-13 01:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0022_uploadedimage'),
        ('blog', '0003_blogpagegallerimage'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BlogPageGallerImage',
            new_name='BlogPageGalleryImage',
        ),
    ]
